// Generated types for Supabase Database
// This file is automatically generated and updated by Supabase

import { Database as DatabaseGenerated } from '@/lib/supabase/database.types';

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database extends DatabaseGenerated {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          first_name: string | null
          last_name: string | null
          stripe_customer_id: string | null
          onboarding_data: Json | null
          onboarding_completed: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          first_name?: string | null
          last_name?: string | null
          stripe_customer_id?: string | null
          onboarding_data?: Json | null
          onboarding_completed?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          first_name?: string | null
          last_name?: string | null
          stripe_customer_id?: string | null
          onboarding_data?: Json | null
          onboarding_completed?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      user_stockpile: {
        Row: {
          id: string
          user_id: string
          caliber_id: string
          caliber_name: string
          current_rounds: number
          target_rounds: number
          monthly_allocation: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          caliber_id: string
          caliber_name: string
          current_rounds?: number
          target_rounds?: number
          monthly_allocation: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          caliber_id?: string
          caliber_name?: string
          current_rounds?: number
          target_rounds?: number
          monthly_allocation?: number
          created_at?: string
          updated_at?: string
        }
      }
      shipping_preferences: {
        Row: {
          id: string
          user_id: string
          trigger_type: 'round_count' | 'value_threshold' | 'time_interval' | 'manual'
          trigger_value: number | null
          trigger_unit: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          trigger_type: 'round_count' | 'value_threshold' | 'time_interval' | 'manual'
          trigger_value?: number | null
          trigger_unit?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          trigger_type?: 'round_count' | 'value_threshold' | 'time_interval' | 'manual'
          trigger_value?: number | null
          trigger_unit?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      onboarding_completions: {
        Row: {
          id: string
          user_id: string
          completed_at: string
          metadata: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          completed_at?: string
          metadata?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          completed_at?: string
          metadata?: Json | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      complete_user_onboarding: {
        Args: {
          p_user_id: string
          p_onboarding_data: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Re-export generated types for convenience
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

export type Profile = Tables<'profiles'>
export type UserStockpile = Tables<'user_stockpile'>
export type ShippingPreference = Tables<'shipping_preferences'>
export type OnboardingCompletion = Tables<'onboarding_completions'>
